services:
  web:
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./requirements.txt:/app/requirements.txt
    entrypoint: []
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
