"""init migration

Revision ID: 24dcb049c4ac
Revises: 
Create Date: 2025-05-20 18:17:49.125629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24dcb049c4ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrobbles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('track', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('playback_date', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrobbles_id'), 'scrobbles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrobbles_id'), table_name='scrobbles')
    op.drop_table('scrobbles')
    # ### end Alembic commands ###
