"""remove track_id from scrobbles

Revision ID: c211f4fc83bf
Revises: 24dcb049c4ac
Create Date: 2025-05-22 00:15:09.951482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c211f4fc83bf'
down_revision: Union[str, None] = '24dcb049c4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrobbles', 'track_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrobbles', sa.Column('track_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
